info:
  name: ExamplePostSignupStubConfiguration 1
  type: http
  seq: 1

http:
  method: POST
  url: "{{baseUrl}}/test-only/post-signup/config"
  body:
    type: json
    data: |-
      {
        "subscriptionId": "{{subscriptionId}}",
        "getSubscriptionAndPostRetrieveCustomerId": {
          "api": "GetSubscription",
          "status": 500
        }
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
