info:
  name: configure 503 response
  type: http
  seq: 5

http:
  method: POST
  url: "{{baseUrl}}/test-only/post-signup/config"
  body:
    type: json
    data: |-
      {
        "subscriptionId": "{{subscriptionId}}",
        "getSubscriptionAndPostRetrieveCustomerId": {
          "api": "PostRetrieveCustomerId",
          "getSubscription": {"utr": "{{utr}}", "crn": "{{crn}}"},
          "status": 503,
          "defaultBodyOverride": {{payload}}
        }
      }
  auth: inherit

runtime:
  scripts:
    - type: before-request
      code: |-
        const payload = JSON.stringify(`{
          "origin": "HIP",
          "response": {
            "type": "Type of Failure",
            "reason": "Reason for Failure"
          }
        }`);

        bru.setVar("payload", payload);

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
