info:
  name: configure 404 response
  type: http
  seq: 4

http:
  method: POST
  url: "{{baseUrl}}/test-only/post-signup/config"
  body:
    type: json
    data: |-
      {
        "subscriptionId": "{{subscriptionId}}",
        "getSubscriptionAndPostRetrieveCustomerId": {
          "api": "PostRetrieveCustomerId",
          "getSubscription": {"utr": "{{utr}}", "crn": "{{crn}}"},
          "status": 404
        }
      }
  auth: inherit

runtime:
  scripts:
    - type: before-request
      code: |-
        const payload = JSON.stringify(`{
          "example": "body"
        }`);

        bru.setVar("payload", payload);

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
